# Copyright 2018 Menne Kamminga <kamminga DOT m AT gmail DOT com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
FROM debian:stable-slim
LABEL maintainer="Menne Kamminga <kamminga.m@gmail.com>"
LABEL description="Filesystem tests for the cloudcryptfs project"

RUN apt-get update && apt-get install -y \
    rsync \
		fuse \
		libcrypto++6 \
		libsodium23 \
		libtest-harness-perl \
    gdb \
    xxd \
&& mkdir /output \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN dd if=/dev/urandom of=/testfile1 bs=1M count=8 iflag=fullblock \
&& dd if=/dev/urandom of=/1mbtestfile bs=1M count=1 iflag=fullblock \ 
&& dd if=/dev/urandom of=/bigfile bs=1M count=150 iflag=fullblock \ 
&& cat /1mbtestfile /1mbtestfile /1mbtestfile /1mbtestfile > /testfile2



EXPOSE 873



COPY cloudCryptFS.docker .cloudCryptFS.docker.dbg do_test.sh fstest /


ENTRYPOINT ["/do_test.sh"]
VOLUME /output
